source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'FRCDataManager_Example' do
  pod 'FRCDataManager', :path => '../'
end

target 'FRCDataManager_Tests' do
  pod 'FRCDataManager', :path => '../'
  #pod 'Quick', '~> 0.8.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
